@startuml
!pragma teoz true


skinparam wrapWidth 800
autonumber 1

actor "Test" as test
entity "OrderService" as orderService #123456

test -[#123456]> orderService: POST: /checkout
note left
{
  "item": "egg"
}
end note
orderService -[#123456]-> test: OK
note right
{
  "ok": true
}
end note
@enduml
