@startuml
!pragma teoz true


skinparam wrapWidth 800
autonumber 1

actor "Test" as test
entity "ApiService" as apiService

test -> apiService: POST: /graphql\n(query GetData)
note left
query GetData($flag: Boolean!) {
  user {
    id
    name @include(if: $flag) short: emailAddress
    ...userFields
    ... on Admin {
      role
    }
  }
}

fragment userFields on User {
  createdAt
  status
}

variables:
{
  "flag": true
}
end note
apiService --> test: OK
note right
{
  "data": {
    "user": {
      "id": "1"
    }
  }
}
end note
@enduml
