@startuml
!pragma teoz true


skinparam wrapWidth 800
autonumber 1

actor "Test" as test
entity "OrderService" as orderService

test -> orderService: POST: /checkout
note left
<color:gray>[Accept=application/json]
<color:gray>[Content-Type=application/json]

{
  "item": "egg"
}
end note
orderService --> test: OK
note right
<color:gray>[Content-Type=application/json]
<color:gray>[X-Trace=abc-123]

{
  "ok": true
}
end note
@enduml
