@startuml
!pragma teoz true


skinparam wrapWidth 800
autonumber 1

actor "Test" as test
entity "OrderService" as orderService

test -> orderService: [[#iflow-00000000-0000-0000-0000-000000000101 POST: /checkout]]
note left
{
  "item": "egg"
}
end note
orderService --> test: OK
note right
{
  "ok": true
}
end note
@enduml
