// @ts-check
const { defineConfig, devices } = require('@playwright/test');

// Pixel verification for the Kronikol4J browser renderer. Loads a real, self-contained report
// (generated by `./gradlew :kronikol4j-report:generatePlaywrightFixture`) from a local file and
// confirms the PlantUML-WASM pipeline actually paints an SVG — no network, no mocking.
module.exports = defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: 0,
  reporter: [['list']],
  timeout: 60_000,
  expect: { timeout: 30_000 },
  use: {
    trace: 'retain-on-failure',
    // file:// pages need no baseURL; specs resolve the report path themselves.
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
